[tool.poetry]
name="llmassist"
version="0.1.0"
description=""
authors = ["dmitryulkin <dmulkin@yandex.ru>"]
license = "MIT License"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.1"
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
