services:
  devcontainer:
    container_name: "llmassist_devcontainer"
    build:
      # the path of the Dockerfile and context is relative to the *primary* docker-compose.yml
      # (the first in the devcontainer.json "dockerComposeFile" array).
      # This case assumes your primary file is in the subfolder of the root of your project.
      context: ..
      dockerfile: build/Dockerfile
      target: dev
      args:
        USER_NAME: ${DEVCONTAINER_USERNAME:-nonroot}
        USER_ID: ${DEVCONTAINER_USER_ID:-5678}
    image: llmassist_devcontainer
    # local path to remote path mapping with anonimous volume
    # '..' because of context: ..
    # :delegated means changes in the container may not be immediately reflected on the host
    # :cached means changes in the host may not be immediately reflected on the container
    # :consistent means identical view all the time
    volumes:
      - ..:/workspace:cached
    # devcontainer uses localhost net
    network_mode: host
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # For Windows Docker Desktop  - NVIDIA driver with paravirtualization
    # is required in the system. It is available on win 11 from NVIDIA website
    # and on win 10 from subscription.
    # For WSL2 Docker Core - nvidia-containe-toolkit is required
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
